#!/usr/bin/env bash
DEVELOPMENT_DIRECTORY=${DEVELOPMENT_DIRECTORY:-${HOME}}
SDK_DOWNLOAD_URL="https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-211.0.0-linux-x86_64.tar.gz"

DOWNLOAD_TARGET=/tmp/$(basename ${SDK_DOWNLOAD_URL})

wget -c -O ${DOWNLOAD_TARGET} ${SDK_DOWNLOAD_URL}

cd ${DEVELOPMENT_DIRECTORY}
tar -xzf ${DOWNLOAD_TARGET} 
